CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO roles(name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES ('MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES ('VIEWER') ON CONFLICT DO NOTHING;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS role_id BIGINT;

ALTER TABLE users
ADD CONSTRAINT fk_role
FOREIGN KEY (role_id)
REFERENCES roles(id);